# TODO: Lower-level Makefile that builds our data structures

# TARGET = queue frame_table pcb pipe tty
# OBJS = $(TARGET).o 

# #Use the gcc compiler for compiling and linking
# CC = gcc

# DDIR58 = $(YALNIX_FRAMEWORK)
# LIBDIR = $(DDIR58)/lib
# INCDIR = $(DDIR58)/include
# ETCDIR = $(DDIR58)/etc
# #LIBRARY_PATH = $(ETCDIR)/linking/lib

# # any extra loading flags...
# LD_EXTRA = 

# KERNEL_LIBS = $(LIBDIR)/libkernel.a $(LIBDIR)/libhardware.so

# # the "kernel.x" argument tells the loader to use the memory layout in the kernel.x file..
# KERNEL_LDFLAGS = $(LD_EXTRA) -L$(LIBDIR) -lkernel  -Wl,-T,$(ETCDIR)/kernel.x  -Wl,-R$(LIBDIR)  -lhardware
# LINK_KERNEL = $(LINK.c)

# $(TARGET): $(KERNEL_OBJS) $(KERNEL_LIBS) $(KERNEL_INCS)
# 	$(LINK_KERNEL) -o $@ $(KERNEL_OBJS) $(KERNEL_LDFLAGS)